# Generated by Django 2.2.6 on 2019-10-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map_locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tw', models.CharField(max_length=25, null=True)),
                ('text', models.CharField(max_length=1000, null=True)),
                ('date', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
